version: '3.8'
name : rest-mocked
services:
  back:
    container_name: rest-mocked
    image: json-server
    ports:
      - "3000:3000"
    volumes:
      - ./rest/db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0