version: '3.8'
name : rest-mocked
services:
  back:
    container_name: rest-mocked
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - rest-db:/data
      
volumes:
  rest-db: {}   